spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gym_management
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    open-in-view: true
  gym-management:
    security:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 7 days