spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gym_management
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    open-in-view: true
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connection-timeout: 5000
          timeout: 3000
          write timeout: 5000
server:
  error:
    include-message: always

# jwt properties
jwt:
  expiration: 86400000 # 1 day
  refresh-expiration: 604800000 # 7 days
  secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

# email validator properties
email-regex: "^(?=.{1,64}@)[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@[^-][A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$"

# domain url
domain: http://localhost:8080

#UUID token expiration time
uuid:
  token:
    expiration: 15 # in minutes